apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sklearn-iris
  namespace: models
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  predictor:
    serviceAccountName: kserve-model
    model:
      modelFormat:
        name: sklearn
        version: "1"
      storageUri: s3://models/sklearn-iris
      resources:
        requests: { cpu: 100m, memory: 512Mi }
        limits: { cpu: "1", memory: 1Gi }
