server:
  service:
    type: NodePort
    nodePort: 30900
  persistentVolume:
    enabled: true
    existingClaim: prometheus-pvc
  extraInitContainers:
    - name: volume-permissions
      image: busybox:1.36
      command: [sh, -c, 'chown -R 65534:65534 /data']
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      volumeMounts:
        - name: storage-volume
          mountPath: /data
  additionalScrapeConfigs:
    - job_name: mlflow
      metrics_path: /metrics
      static_configs:
        - targets: [mlflow.mlops.svc.cluster.local:5000]
    - job_name: minio
      metrics_path: /minio/prometheus/metrics
      static_configs:
        - targets: [minio.mlops.svc.cluster.local:9000]
alertmanager:
  persistentVolume:
    enabled: true
prometheus-node-exporter:
  enabled: false
