apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "4" }
spec:
  project: mlops-platform
  sources:
    - repoURL: quay.io/jetstack/charts
      chart: cert-manager
      targetRevision: v1.17.0
      helm: { valueFiles: ["$values/infra/platform/helm-values/cert-manager/values.yaml"] }
    - repoURL: https://github.com/umeshchhabra/mlops-foundry.git
      targetRevision: main
      ref: values
  destination: { server: https://kubernetes.default.svc, namespace: cert-manager }
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
