apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-crd
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "5" }
spec:
  project: mlops-platform
  source:
    repoURL: oci://ghcr.io/kserve/charts
    chart: kserve-crd
    targetRevision: v0.20.0
  destination: { server: https://kubernetes.default.svc, namespace: kserve }
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true,ServerSideApply=true]
