apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mlops-platform
  namespace: argocd
spec:
  description: Local MLOps platform services
  sourceRepos:
    - https://github.com/umeshchhabra/mlops-foundry.git
    - https://airflow.apache.org
    - https://argoproj.github.io/argo-helm
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://jupyterhub.github.io/helm-chart/
  destinations:
    - namespace: mlops
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: ""
      kind: PersistentVolume
    - group: ""
      kind: PersistentVolumeClaim
    - group: storage.k8s.io
      kind: StorageClass
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
