apiVersion: v1
kind: Namespace
metadata: { name: mlops }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: postgres-pvc, namespace: mlops }
spec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 5Gi } } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: minio-pvc, namespace: mlops }
spec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 10Gi } } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: prometheus-pvc, namespace: mlops }
spec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 10Gi } } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: airflow-pvc, namespace: mlops }
spec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 5Gi } } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: grafana-pvc, namespace: mlops }
spec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 2Gi } } }
